
export const ROLES = {
  SUPER_ADMIN: "SUPER_ADMIN",
  ADMIN: "ADMIN",
  PHARMACIST: "PHARMACIST",
  BILLING_STAFF: "BILLING_STAFF",
  RECEPTIONIST: "RECEPTIONIST",
} as const;

export type UserRole = keyof typeof ROLES;

export const PERMISSIONS = {
  DASHBOARD_VIEW: "DASHBOARD_VIEW",

  MEDICINE_VIEW: "MEDICINE_VIEW",
  MEDICINE_CREATE: "MEDICINE_CREATE",
  MEDICINE_UPDATE: "MEDICINE_UPDATE",
  MEDICINE_DELETE: "MEDICINE_DELETE",

  INVENTORY_VIEW: "INVENTORY_VIEW",
  INVENTORY_MANAGE: "INVENTORY_MANAGE",

  PURCHASE_VIEW: "PURCHASE_VIEW",
  PURCHASE_CREATE: "PURCHASE_CREATE",

  SALES_VIEW: "SALES_VIEW",
  SALES_CREATE: "SALES_CREATE",

  CUSTOMER_VIEW: "CUSTOMER_VIEW",
  CUSTOMER_MANAGE: "CUSTOMER_MANAGE",

  DOCTOR_VIEW: "DOCTOR_VIEW",
  DOCTOR_MANAGE: "DOCTOR_MANAGE",

  APPOINTMENT_VIEW: "APPOINTMENT_VIEW",
  APPOINTMENT_MANAGE: "APPOINTMENT_MANAGE",

  REPORT_VIEW: "REPORT_VIEW",

  USER_VIEW: "USER_VIEW",
  USER_MANAGE: "USER_MANAGE",

  SETTINGS_MANAGE: "SETTINGS_MANAGE",
} as const;

export type Permission =
  (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

export const ROLE_PERMISSIONS: Record<UserRole, Permission[]> = {
  SUPER_ADMIN: Object.values(PERMISSIONS),

  ADMIN: [
    PERMISSIONS.DASHBOARD_VIEW,

    PERMISSIONS.MEDICINE_VIEW,
    PERMISSIONS.MEDICINE_CREATE,
    PERMISSIONS.MEDICINE_UPDATE,
    PERMISSIONS.MEDICINE_DELETE,

    PERMISSIONS.INVENTORY_VIEW,
    PERMISSIONS.INVENTORY_MANAGE,

    PERMISSIONS.PURCHASE_VIEW,
    PERMISSIONS.PURCHASE_CREATE,

    PERMISSIONS.SALES_VIEW,
    PERMISSIONS.SALES_CREATE,

    PERMISSIONS.CUSTOMER_VIEW,
    PERMISSIONS.CUSTOMER_MANAGE,

    PERMISSIONS.DOCTOR_VIEW,
    PERMISSIONS.DOCTOR_MANAGE,

    PERMISSIONS.APPOINTMENT_VIEW,
    PERMISSIONS.APPOINTMENT_MANAGE,

    PERMISSIONS.REPORT_VIEW,

    PERMISSIONS.USER_VIEW,
    PERMISSIONS.USER_MANAGE,
  ],

  PHARMACIST: [
    PERMISSIONS.DASHBOARD_VIEW,

    PERMISSIONS.MEDICINE_VIEW,
    PERMISSIONS.MEDICINE_CREATE,
    PERMISSIONS.MEDICINE_UPDATE,

    PERMISSIONS.INVENTORY_VIEW,
    PERMISSIONS.INVENTORY_MANAGE,

    PERMISSIONS.PURCHASE_VIEW,
    PERMISSIONS.PURCHASE_CREATE,

    PERMISSIONS.SALES_VIEW,
    PERMISSIONS.SALES_CREATE,

    PERMISSIONS.CUSTOMER_VIEW,
    PERMISSIONS.CUSTOMER_MANAGE,
  ],

  BILLING_STAFF: [
    PERMISSIONS.DASHBOARD_VIEW,

    PERMISSIONS.MEDICINE_VIEW,

    PERMISSIONS.INVENTORY_VIEW,

    PERMISSIONS.SALES_VIEW,
    PERMISSIONS.SALES_CREATE,

    PERMISSIONS.CUSTOMER_VIEW,
    PERMISSIONS.CUSTOMER_MANAGE,
  ],

  RECEPTIONIST: [
    PERMISSIONS.DASHBOARD_VIEW,

    PERMISSIONS.DOCTOR_VIEW,

    PERMISSIONS.APPOINTMENT_VIEW,
    PERMISSIONS.APPOINTMENT_MANAGE,
  ],
};  

export function hasPermission(
  role: UserRole,
  permission: Permission
) {
  return ROLE_PERMISSIONS[role]?.includes(permission) ?? false;
}